[package]
name = "CRUD"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.8.0"
dotenv = "0.15"
tokio = { version="1.38.0", features=["full"] }
tokio-postgres = "0.7.10"

[[bin]]
name = "server"
path = "src/main.rs"