services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080 
    depends_on:
      - db
    environment:
      DATABASE_URL: "host=db user=Fernando dbname=crud password=Rfm*102030"
    networks:
      - app-network

  db:
    image: postgres:16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Fernando -d crud"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: always
    environment:
      POSTGRES_DB: crud 
      POSTGRES_USER: Fernando 
      POSTGRES_PASSWORD: Rfm*102030 
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge