version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_LOG=info
      - DATABASE_URL=postgres://postgres:cucuz_de_frango_com_ovo_e_bom@db:5432/CRUD
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: grupinho_do_henrique
      POSTGRES_PASSWORD: cucuz_de_frango_com_ovo_e_bom
      POSTGRES_DB: CRUD
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
